force-app/main/default/objects/Calendar_Invite__c/Calendar_Invite__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Calendar Invite</label>
</CustomObject>

force-app/main/default/objects/Calendar_Invite__c/fields/Default_Description__c.field-meta.xml
<CustomField>
    <fullName>Default_Description__c</fullName>
    <defaultValue>&quot;&quot;</defaultValue>
    <description>This is the default email/invite description of the event invite if you decide to disable the &quot;required&quot; attribute of the &quot;Description&quot; field.</description>
    <label>Default Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Calendar_Invite__c/fields/Default_Email_Template__c.field-meta.xml
<CustomField>
    <fullName>Default_Email_Template__c</fullName>
    <defaultValue>&quot;Calendar Invite&quot;</defaultValue>
    <description>This is the default email/page template of the event invite if you decide to disable the &quot;required&quot; attribute of the &quot;Event Template&quot; field.</description>
    <label>Default Email Template</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Calendar_Invite__c/fields/Default_Org_Wide_Sender__c.field-meta.xml
<CustomField>
    <fullName>Default_Org_Wide_Sender__c</fullName>
    <defaultValue>&quot;Default Organizer&quot;</defaultValue>
    <description>This is the default sender of the event invite if you decide to disable the &quot;required&quot; attribute of the &quot;Event Organizer&quot; field.</description>
    <label>Default Org Wide Sender</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Calendar_Invite__c/fields/Default_Subject__c.field-meta.xml
<CustomField>
    <fullName>Default_Subject__c</fullName>
    <defaultValue>&quot;Please RSVP&quot;</defaultValue>
    <description>This is the default email/invite subject of the event invite if you decide to disable the &quot;required&quot; attribute of the &quot;Subject&quot; field.</description>
    <label>Default Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Calendar_Invite__c/fields/Event_Record_ID__c.field-meta.xml
<CustomField>
    <fullName>Event_Record_ID__c</fullName>
    <defaultValue>&quot;0120m0000008dYX&quot;</defaultValue>
    <description>Event Record Type ID of Calendar Invite type Events. Leave blank if all Events are to sent calendar invites.</description>
    <label>Event Record ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventInvite__c/EventInvite__c.object-meta.xml
<CustomObject>
    <label>Event Invite</label>
    <nameField>
        <displayFormat>EI-{000000}</displayFormat>
        <label>Event Invite ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Invites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EventInvite__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Active&quot;</defaultValue>
    <inlineHelpText>This will show &quot;Active&quot; unless then event has been canceled, in which case it will show &quot;Canceled&quot;</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EventInviteResponse__c/EventInviteResponse__c.object-meta.xml
<CustomObject>
    <label>Event Invite Response</label>
    <nameField>
        <displayFormat>EIR-{000000}</displayFormat>
        <label>Event Invite Response ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Invite Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EventInviteResponse__c/fields/event_invite__c.field-meta.xml
<CustomField>
    <fullName>event_invite__c</fullName>
    <inlineHelpText>The event invite this response is in regard to.</inlineHelpText>
    <label>Event Invite</label>
    <referenceTo>EventInvite__c</referenceTo>
    <relationshipLabel>Event Invite Responses</relationshipLabel>
    <relationshipName>Event_Invite_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EventInviteResponse__c/fields/Invite_Source__c.field-meta.xml
<CustomField>
    <fullName>Invite_Source__c</fullName>
    <defaultValue>&quot;Company&quot;</defaultValue>
    <inlineHelpText>This tells us the source of the invite. Either we (Company) sent the invite, or one of the invitees added another invitee on the Invite Detail Page, or the invitee forwarded the email to another who accepted the invite.</inlineHelpText>
    <label>Invite Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Company</fullName>
            </value>
            <value>
                <fullName>Added Via Invite</fullName>
            </value>
            <value>
                <fullName>Email Forward</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EventInviteResponse__c/fields/Invitee__c.field-meta.xml
<CustomField>
    <fullName>Invitee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is the person for whom this invite response applies.</inlineHelpText>
    <label>Invitee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Invite Responses</relationshipLabel>
    <relationshipName>Event_Invite_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EventInviteResponse__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <defaultValue>&quot;Not Responded&quot;</defaultValue>
    <inlineHelpText>This shows the event invitee&apos;s response: Accepted = Yes going, Undecided = Maybe going, Declined = No not going, Not Responded = Invitee has not yet chosen a response. If invite was canceled by Salesforce user this will show &quot;Canceled&quot;</inlineHelpText>
    <label>Response</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Undecided</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Not Responded</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EventInviteResponse__c/fields/Response_Date__c.field-meta.xml
<CustomField>
    <fullName>Response_Date__c</fullName>
    <inlineHelpText>The date/time the response was last updated.</inlineHelpText>
    <label>Response Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/CalendarInvitePages.cls
global class CalendarInvitePages extends CalendarInviteBase
{
  global CalendarInvitePages(ApexPages.StandardController stdC)
  {
    settings = Calendar_Invite__c.getInstance(Userinfo.getUserId());
    myEvent = new Event();
    
    try
    {
      myCase = [SELECT Id, Subject, Description, ContactId
                     , Event_Invite__c, Invite_Date_Time__c, Invite_End_Date_Time__c
                     , Invite_Destination__r.Name, Invite_Destination__r.BillingAddress
                  FROM Case
                 WHERE Id =: stdC.getId()
                 LIMIT 1
               ];
      
      myEvent.RecordTypeId = settings.Event_Record_ID__c;
      myEvent.Subject = myCase.Subject;
      myEvent.Description = myCase.Description;
      myEvent.Location = CalculateLocation(myCase);
      myEvent.StartDateTime = myCase.Invite_Date_Time__c;
      myEvent.EndDateTime = CalculateEndDate(myCase);
      myEvent.WhoId = myCase.ContactId;
      myEvent.WhatId = myCase.Id;

      myEvent.Event_Organizer__c = settings.Default_Org_Wide_Sender__c;
      myEvent.Event_Invite_Template__c = settings.Default_Email_Template__c;

      myEvent.Invite_Email_Subject__c = settings.Default_Subject__c;
      myEvent.Invite_Email_Body__c = settings.Default_Description__c;

      myObjectType = 'case';
    }
    catch(Exception e){}
    try
    {
      myContact = (Contact)stdC.getRecord();
      myObjectType = 'contact';
    }
    catch(Exception e){}
    try
    {
        myEventInviteResponse = (EventInviteResponse__c)stdC.getRecord();
        myObjectType = 'eventinviteresponse';
    }
    catch(Exception e){}
    try
    {
        myEventInvite = (EventInvite__c)stdC.getRecord();
        myObjectType = 'eventinvite';
    }
    catch(Exception e){}
  }
  global CalendarInvitePages() {}
  
  public InviteResponse ResponseDetails
  {
      get
      {
        LoadResponseInput inputs = new LoadResponseInput();
        inputs.eirId = eirId;
        
        CalendarInvite calInv = new CalendarInvite();
        return calInv.LoadResponseDetailInner(inputs);
      }
      set;
  }
  
  public PageReference SendCalendarInvite()
  {
    if (myObjectType == 'case')
    {
      // First delete existing calendar invite
      if (myCase.Event_Invite__c != null)
      {
        Event myE = getEvent(null, myCase.Event_Invite__c, null);
        List<EventInviteResponse__c> myEIRs = [SELECT Id FROM EventInviteResponse__c WHERE event_invite__c =: myCase.Event_Invite__c];
        
        for (EventInviteResponse__c eir : myEIRs)
        {
          delete eir;
        }
        //delete myEI;
        Database.delete(myCase.Event_Invite__c);
        delete myE;
      }
      insert myEvent;
    }

    return null;
  }
  
  public PageReference ResendInvite() // Called from Event Invite Response for resending invite email
  {
      Calendar_Invite__c settings = Calendar_Invite__c.getInstance(Userinfo.getUserId());
      
      Event e = getEvent(null, myEventInviteResponse.event_invite__c, null);
      
      EmailData myData = GetEmailDataFromEvent(e, settings);
      
      SendEmail(myEventInviteResponse.invitee__c, myEventInviteResponse.Id, myData.EmailTemplateId, myData.OrgWideEmailAddressId, 'Reminder: ' + e.invite_email_subject__c, e.invite_email_body__c);
      
      PageReference eirPage = new PageReference('/' + myEventInviteResponse.id);
      eirPage.setRedirect(true);
      return eirPage;
  }
  
  public PageReference ResendInvites() // Called from Event Invite (or Case) for resending invite emails to all invitees
  { 
      Calendar_Invite__c settings = Calendar_Invite__c.getInstance(Userinfo.getUserId());
      
      Id eiId;
      Boolean redir = false;
      
      if (myEventInvite == null)
      {
          eiId = myCase.Event_Invite__c;
      }
      else
      {
          eiId = myEventInvite.Id;
          redir = true;
      }
      
      Event e = getEvent(null, eiId, null);
      
      List<EventInviteResponse__c> eirs = [SELECT Id, Invite_Source__c, event_invite__c, invitee__c 
                                             FROM EventInviteResponse__c 
                                            WHERE Event_Invite__c =: eiId
                                              AND Response__c <> 'Canceled'
                                          ];
      
      EmailData myData = GetEmailDataFromEvent(e, settings);
      
      for (EventInviteResponse__c eir : eirs)
      {
          SendEmail(eir.invitee__c, eir.Id, myData.EmailTemplateId, myData.OrgWideEmailAddressId, 'Reminder: ' + e.invite_email_subject__c, e.invite_email_body__c);
      }
      
      if (redir)
      {
          PageReference eiPage = new PageReference('/' + eiId);
          eiPage.setRedirect(true);
          return eiPage;
      }
      return null;
  }
  
  public PageReference CancelInvite() // Called from Event Invite Response for sending cancel invite email
  {
      Calendar_Invite__c settings = Calendar_Invite__c.getInstance(Userinfo.getUserId());
      
      Event e = getEvent(null, myEventInviteResponse.event_invite__c, null);
      myEventInviteResponse.response__c = 'Canceled';
      myEventInviteResponse.response_date__c = DateTime.Now();
      update myEventInviteResponse;
      
      EmailData myData = GetEmailDataFromEvent(e, settings);
      
      SendEmail(myEventInviteResponse.invitee__c, myEventInviteResponse.Id, myData.EmailTemplateId, myData.OrgWideEmailAddressId, 'Canceled: ' + e.invite_email_subject__c, e.invite_email_body__c);
      
      PageReference eirPage = new PageReference('/' + myEventInviteResponse.id);
      eirPage.setRedirect(true);
      return eirPage;
  }
  
  public PageReference CancelInvites() // Called from Event Invite for sending cancel invite emails to all invitees
  { 
      Calendar_Invite__c settings = Calendar_Invite__c.getInstance(Userinfo.getUserId());
      
      Event e = getEvent(null, myEventInvite.Id, null);
      
      List<EventInviteResponse__c> eirs = [SELECT Id, Invite_Source__c, event_invite__c, invitee__c 
                                             FROM EventInviteResponse__c 
                                            WHERE Event_Invite__c =: myEventInvite.Id
                                              AND Response__c <> 'Canceled'
                                          ];
      myEventInvite.Status__c = 'Canceled';
      
      EmailData myData = GetEmailDataFromEvent(e, settings);
      
      for (EventInviteResponse__c eir : eirs)
      {
          eir.response__c = 'Canceled';
          eir.response_date__c = DateTime.Now();
          update eir;
          SendEmail(eir.invitee__c, eir.Id, myData.EmailTemplateId, myData.OrgWideEmailAddressId, 'Canceled: ' + e.invite_email_subject__c, e.invite_email_body__c);
      }
      
      PageReference eiPage = new PageReference('/' + myEventInvite.id);
      eiPage.setRedirect(true);
      return eiPage;
  }
  
}