force-app/main/default/objects/Calendar_Invite__c/Calendar_Invite__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Calendar Invite</label>
</CustomObject>

force-app/main/default/objects/Calendar_Invite__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <inlineHelpText>The name of the company/organization sending the calendar invites.</inlineHelpText>
    <label>Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Calendar_Invite__c/fields/Company_Website__c.field-meta.xml
<CustomField>
    <fullName>Company_Website__c</fullName>
    <inlineHelpText>The website of the company/organization sending the calendar invites.</inlineHelpText>
    <label>Company Website</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Calendar_Invite__c/fields/Site_URL__c.field-meta.xml
<CustomField>
    <fullName>Site_URL__c</fullName>
    <defaultValue>&quot;https://3st-invites-developer-edition.na73.force.com/invite&quot;</defaultValue>
    <description>Custom url for hosting calendar invites at branded location. You will need to create a Site in Salesforce that corresponds to the below setting. Leave blank to host from regular Salesforce domain (e.g. na1.salesforce.com/apex/).</description>
    <label>Site URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventInviteResponse__c/EventInviteResponse__c.object-meta.xml
<CustomObject>
    <label>Event Invite Response</label>
    <nameField>
        <displayFormat>EIR-{000000}</displayFormat>
        <label>Event Invite Response ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Invite Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EventInviteResponse__c/fields/event_invite__c.field-meta.xml
<CustomField>
    <fullName>event_invite__c</fullName>
    <inlineHelpText>The event invite this response is in regard to.</inlineHelpText>
    <label>Event Invite</label>
    <referenceTo>EventInvite__c</referenceTo>
    <relationshipLabel>Event Invite Responses</relationshipLabel>
    <relationshipName>Event_Invite_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EventInviteResponse__c/fields/Invite_Source__c.field-meta.xml
<CustomField>
    <fullName>Invite_Source__c</fullName>
    <defaultValue>&quot;Company&quot;</defaultValue>
    <inlineHelpText>This tells us the source of the invite. Either we (Company) sent the invite, or one of the invitees added another invitee on the Invite Detail Page, or the invitee forwarded the email to another who accepted the invite.</inlineHelpText>
    <label>Invite Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Company</fullName>
            </value>
            <value>
                <fullName>Added Via Invite</fullName>
            </value>
            <value>
                <fullName>Email Forward</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EventInviteResponse__c/fields/Invite_URL__c.field-meta.xml
<CustomField>
    <fullName>Invite_URL__c</fullName>
    <formula>HYPERLINK($Setup.Calendar_Invite__c.Site_URL__c &amp; &quot;?eirId=&quot; &amp; CASESAFEID(Id), &quot;Invite Link&quot;)</formula>
    <label>Invite URL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventInviteResponse__c/fields/Invitee__c.field-meta.xml
<CustomField>
    <fullName>Invitee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is the person for whom this invite response applies.</inlineHelpText>
    <label>Invitee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Invite Responses</relationshipLabel>
    <relationshipName>Event_Invite_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EventInviteResponse__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <defaultValue>&quot;Not Responded&quot;</defaultValue>
    <inlineHelpText>This shows the event invitee&apos;s response: Accepted = Yes going, Undecided = Maybe going, Declined = No not going, Not Responded = Invitee has not yet chosen a response. If invite was canceled by Salesforce user this will show &quot;Canceled&quot;</inlineHelpText>
    <label>Response</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Undecided</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Not Responded</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EventInviteResponse__c/fields/Response_Date__c.field-meta.xml
<CustomField>
    <fullName>Response_Date__c</fullName>
    <inlineHelpText>The date/time the response was last updated.</inlineHelpText>
    <label>Response Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/EventInviteResponse__c/fields/Response_Note__c.field-meta.xml
<CustomField>
    <fullName>Response_Note__c</fullName>
    <inlineHelpText>This is a note from the respondent in regard to their response.</inlineHelpText>
    <label>Response Note</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/CalendarInvite.cls
global class CalendarInvite extends CalendarInviteBase
{
  global CalendarInvite(ApexPages.StandardController stdC) {}
  global CalendarInvite() {}


  @RemoteAction
  global static string LoadResponseDetail(string input)
  {
    LoadResponseInput inputs = (LoadResponseInput)JSON.deserialize(input, LoadResponseInput.class);
    CalendarInvite calInv = new CalendarInvite();
    return JSON.serialize(calInv.LoadResponseDetailInner(inputs));
  }
  
  public InviteResponse ResponseDetails
  {
      get { return (new CalendarInvitePages()).ResponseDetails; }
      set;
  }
  
  
  public InviteResponse LoadResponseDetailInner(LoadResponseInput inputs)
  {
    Event e = null;
    List<EventInviteResponse__c> eirList = new List<EventInviteResponse__c>();
    
    if (inputs.eiId == null || inputs.eiId == '')
    {
        EventInviteResponse__c myeir = null;
        try {
            myeir = [SELECT Id, Event_Invite__c, Invitee__r.Email FROM EventInviteResponse__c WHERE Id = :inputs.eirId];
            inputs.eiId = myeir.Event_Invite__c;
            inputs.email = myeir.Invitee__r.Email;
        } catch (Exception ex) {
            // Eat; handled below
        }
    }
        
    try {
        e = getEvent(null, inputs.eiId, null);
        eirList = [SELECT Id, Event_Invite__c, Response__c, Response_Date__c, Response_Note__c, Invite_URL__c
                        , Invitee__r.FirstName, Invitee__r.LastName, Invitee__r.Email, Invitee__r.Merged_Timezone__c
                     FROM EventInviteResponse__c 
                    WHERE Event_Invite__c = :inputs.eiId
                      AND (Response__c <> 'Canceled' OR Id =: inputs.eirId)
                  ];
    } catch (Exception ex)  {
        // Eat; handled below
    }
    
    // Add inputs to return value
    InviteResponse rv = new InviteResponse(inputs);
    if (e == null || eirList == null || eirList.size() == 0)
    {
      rv.success = false;
      return rv;
    }
    
    // Add event details to return value
    rv.subject = e.subject;
    rv.description = e.description;
    rv.location = e.location;
    rv.startdt = e.StartDateTime;
    rv.enddt = e.EndDateTime;

    
    Calendar_Invite__c settings = Calendar_Invite__c.getInstance(Userinfo.getUserId());
    EmailData myData = GetEmailDataFromEvent(e, settings);
    rv.organizer = myData.organizer;
    rv.organizer_email = myData.organizer_email;
    
    rv.company_name = settings.Company_Name__c;
    rv.company_website = settings.Company_Website__c;
    
    String inviteSite = settings.Site_URL__c;
    if (inviteSite == '' || inviteSite == null)
    {
      inviteSite = System.URL.getSalesforceBaseUrl().toExternalForm();
    }
    
    rv.detailURL = inviteSite + '?eirId=' + string.valueOf(inputs.eirId);

    
    // Add invitee details to return value
    integer maxN = eirList.size();
    boolean foundMine = false;
    String tzval = '';
    for (integer ndx = 0; ndx < maxN; ndx++)
    {
      EventInviteResponse__c eir = eirList.get(ndx);
      
      Respondent r = new Respondent();
      
      r.isMe = (eir.Invitee__r.email == inputs.email);
      r.firstname = eir.Invitee__r.FirstName;
      r.lastname = eir.Invitee__r.LastName;
      r.response = eir.Response__c;
      r.email = eir.Invitee__r.Email;
      r.responsedate = (eir.Response_Date__c != null ? eir.Response_Date__c : DateTime.Now());
      r.responsenote = eir.Response_Note__c;
      
      if (r.isMe)
      {
        foundMine = true;
        rv.timezone = eir.Invitee__r.Merged_Timezone__c;
        rv.timezoneshort = rv.timezone.split('\\ ')[0]
                         + rv.timezone.substring(rv.timezone.lastIndexOf('(') - 1);
        //rv.detailURL = eir.Invite_URL__c; // did not return a value for whatever reason
        rv.status = (eir.Response__c == 'Canceled' ? 'CANCELLED' : 'CONFIRMED');
        rv.method = (eir.Response__c == 'Canceled' ? 'CANCEL' : 'REQUEST');
      
        tzval = rv.timezone.split('\\ ')[0].replace('GMT','').replace('+','');
      }
      
      rv.respondents.add(r);
    }
    
    // If we cannot find the requester's record then we return nothing
    if (foundMine == false)
    {
      return new InviteResponse(inputs);
    }
    
    // Set from/to datetime string
    if (isSameDay(rv.startdt, rv.enddt, tzval))
    {
      rv.dateTimeString = formatDate(rv.startdt, tzval)
                        + ' - '
                        + formatTime(rv.enddt, tzval);
    }
    else
    {
      rv.dateTimeString = formatDate(rv.startdt, tzval)
                        + ' - '
                        + formatDate(rv.enddt, tzval);
    }
    rv.startdtStr = rv.startdt.formatGMT('yyyyMMdd\'T\'HHmmss');
    rv.enddtStr = rv.enddt.formatGMT('yyyyMMdd\'T\'HHmmss');
    
    rv.nowStr = DateTime.Now().formatGMT('yyyyMMdd\'T\'HHmmss');
    
    // update Response Dates
    for (integer ndx = 0; ndx < maxN; ndx++)
    {
      Respondent r = rv.respondents.get(ndx);
      r.responsedateString = formatDate(r.responsedate, tzval);
    }

    rv.respondents.sort();
    return rv;
  }

  @RemoteAction
  global static String UpdateTimezone(string input)
  {
    UpdateTimezoneInput inputs = (UpdateTimezoneInput)JSON.deserialize(input, UpdateTimezoneInput.class);
    
    EventInviteResponse__c eir = [SELECT Id, Event_Invite__c, Response__c
                                       , Response_Date__c, Response_Note__c, Invitee__r.Email, Invitee__c
                                    FROM EventInviteResponse__c WHERE Id =: inputs.inputs.eirId LIMIT 1];
    
    UpdateTimezoneResult rv = new UpdateTimezoneResult(inputs);
    if (eir == null)
    {
      return JSON.serialize(rv);
    }
    
    string tzstart = inputs.timezone.split(' ')[0];
    string tzend = inputs.timezone.split(' ')[1];
    
    // TODO: Replace looking up against the field with looking up against the metadata
    
    List<Schema.PicklistEntry> ples = Schema.getGlobalDescribe().get('contact')
                                        .getDescribe().fields.getMap().get('x3st_invites__Timezone__c')
                                        .getDescribe().getPicklistValues();
    
    for (PickListEntry ple : ples)
    {
      string comptz = ple.getValue(); // getLabel();
      if (comptz.startsWith(tzstart) && comptz.endsWith(tzend))
      {
        try
        {
          Contact c = [SELECT id, Timezone__c FROM Contact WHERE id =: eir.Invitee__c LIMIT 1];
          c.Timezone__c = comptz;
          update c;
          rv.success = true;

          return JSON.serialize(rv);
        }
        catch (Exception ex)
        {
          rv.error = ex.getMessage();
          system.debug(ex.getMessage());
        }
      }
    }
    if (rv.error == '')
    {
        rv.error = 'Timezone entry was not found!';
    }
    rv.success = false;

    return JSON.serialize(rv);
  }

  @RemoteAction
  global static String UpdateResponse(string input)
  {
    CalendarInvite calInv = new CalendarInvite();
    UpdateResponseInput inputs = (UpdateResponseInput)JSON.deserialize(input, UpdateResponseInput.class);

    EventInviteResponse__c eir = [SELECT Id, Event_Invite__c, Response__c
                                       , Response_Date__c, Response_Note__c, Invitee__r.Email
                                    FROM EventInviteResponse__c WHERE Id =: inputs.inputs.eirId LIMIT 1];

    UpdateResponseResult rv = new UpdateResponseResult(inputs);
    if (eir == null)
    {
      return JSON.serialize(rv);
    }

    Set<String> validResponses = CalendarInviteBase.getResponseOptions();
    if (!validResponses.contains(inputs.response))
    {
      rv.error = 'Invalid response';
      return JSON.serialize(rv);
    }

    eir.Response__c = inputs.response;
    eir.Response_Note__c = inputs.note;
    eir.Response_Date__c = DateTime.Now();
    try
    {
      update eir;
      return LoadResponseDetail(JSON.serialize(inputs.inputs));
    }
    catch (Exception ex)
    {
      rv.error = ex.getMessage();
    }

    return JSON.serialize(rv);

  }

  @RemoteAction
  global static String SendInvites(string input)
  {
    AddInviteesInput inputs = (AddInviteesInput)JSON.deserialize(input, AddInviteesInput.class);

    EventInviteResponse__c eir = [SELECT Id, Event_Invite__c, Response__c
                                       , Response_Date__c, Response_Note__c, Invitee__r.Id, Invitee__r.Email
                                    FROM EventInviteResponse__c WHERE Id =: inputs.inputs.eirId LIMIT 1];

    InviteResult rv = new InviteResult(inputs);
    if (eir == null)
    {
      return JSON.serialize(rv);
    }

    Contact inviter = [SELECT Id, AccountId FROM Contact WHERE Id =: eir.Invitee__r.Id];

    integer numNew = inputs.newinvitees.size();
    List<EventInviteResponse__c> neirList = new List<EventInviteResponse__c>();
    for (integer ndx = 0; ndx < numNew; ndx++)
    {
      NewInvitee ni = inputs.newinvitees.get(ndx);

      List<Contact> ncList = [SELECT Id, FirstName, LastName, email, title, Company__c, Account.Name FROM Contact WHERE email =: ni.email];
      Contact nc;

      if (ncList.size() == 0)
      {
        nc = new Contact(
          FirstName = ni.FirstName,
          LastName = ni.LastName,
          Email = ni.Email,
          Title = ni.Title,
          Company__c = ni.Company,
          AccountId = inviter.AccountId,
          Contact_Type__c = 'Invite Attendee'
        );
        insert nc;
      }
      /*
      else
      {
        nc = ncList.get(0);
        if (nc.FirstName != ni.FirstName)
        {
          // What to do?
        }
        if (nc.LastName != ni.LastName)
        {
          // What to do?
        }
        if (nc.Title != ni.Title)
        {
          // What to do?
        }
        if (nc.Account.Name != ni.Company)
        {
          // What to do?
        }
      }
      */
      
      EventInviteResponse__c neir = new EventInviteResponse__c (
        event_invite__c = eir.event_invite__c,
        Invite_Source__c = 'Added Via Invite',
        invitee__c = nc.Id
      );
      neirList.add(neir);
    }
    
    try
    {
      insert neirList;
      rv.error = '';
      rv.success = true;
    }
    catch (Exception ex)
    {
      rv.error = ex.getMessage();
    }

    return JSON.serialize(rv);
  }

}